// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum FBSLoopUnit: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case gram = 0
  case gramsPerUnit = 1
  case internationalUnit = 2
  case internationalUnitsPerHour = 3
  case milligramsPerDeciliter = 4
  case milligramsPerDeciliterPerSecond = 5
  case milligramsPerDeciliterPerMinute = 6
  case milligramsPerDeciliterPerInternationalUnit = 7
  case millimolesPerLiter = 8
  case millimolesPerLiterPerSecond = 9
  case millimolesPerLiterPerMinute = 10
  case millimolesPerLiterPerInternationalUnit = 11
  case percent = 12
  case hour = 13
  case minute = 14
  case second = 15

  public static var max: FBSLoopUnit { return .second }
  public static var min: FBSLoopUnit { return .gram }
}


public enum FBSGlucoseCondition: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case belowRange = 0
  case aboveRange = 1

  public static var max: FBSGlucoseCondition { return .aboveRange }
  public static var min: FBSGlucoseCondition { return .belowRange }
}


public enum FBSInsulinDeliveryType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case bolus = 0
  case basal = 1

  public static var max: FBSInsulinDeliveryType { return .basal }
  public static var min: FBSInsulinDeliveryType { return .bolus }
}


public enum FBSFixtureInsulinType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case novolog = 0
  case humalog = 1
  case apidra = 2
  case fiasp = 3
  case lyumjev = 4
  case afrezza = 5

  public static var max: FBSFixtureInsulinType { return .afrezza }
  public static var min: FBSFixtureInsulinType { return .novolog }
}


public enum FBSCarbAbsorptionModel: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case linear = 0
  case piecewiseLinear = 1

  public static var max: FBSCarbAbsorptionModel { return .piecewiseLinear }
  public static var min: FBSCarbAbsorptionModel { return .linear }
}


public enum FBSDoseRecommendationType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case manualBolus = 0
  case automaticBolus = 1
  case tempBasal = 2

  public static var max: FBSDoseRecommendationType { return .tempBasal }
  public static var min: FBSDoseRecommendationType { return .manualBolus }
}


public struct FBSLoopQuantity: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case unit = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var unit: FBSLoopUnit { let o = _accessor.offset(VTOFFSET.unit.v); return o == 0 ? .gram : FBSLoopUnit(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .gram }
  public var value: Double { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startFBSLoopQuantity(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(unit: FBSLoopUnit, _ fbb: inout FlatBufferBuilder) { fbb.add(element: unit.rawValue, def: 0, at: VTOFFSET.unit.p) }
  public static func add(value: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: value, def: 0.0, at: VTOFFSET.value.p) }
  public static func endFBSLoopQuantity(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSLoopQuantity(
    _ fbb: inout FlatBufferBuilder,
    unit: FBSLoopUnit = .gram,
    value: Double = 0.0
  ) -> Offset {
    let __start = FBSLoopQuantity.startFBSLoopQuantity(&fbb)
    FBSLoopQuantity.add(unit: unit, &fbb)
    FBSLoopQuantity.add(value: value, &fbb)
    return FBSLoopQuantity.endFBSLoopQuantity(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.unit.p, fieldName: "unit", required: false, type: FBSLoopUnit.self)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: Double.self)
    _v.finish()
  }
}

public struct FBSFixtureGlucoseSample: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case provenanceIdentifier = 4
    case startDate = 6
    case quantity = 8
    case isDisplayOnly = 10
    case wasUserEntered = 12
    case condition = 14
    case trendRate = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var provenanceIdentifier: String? { let o = _accessor.offset(VTOFFSET.provenanceIdentifier.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var provenanceIdentifierSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.provenanceIdentifier.v) }
  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var quantity: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.quantity.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public var isDisplayOnly: Bool { let o = _accessor.offset(VTOFFSET.isDisplayOnly.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var wasUserEntered: Bool { let o = _accessor.offset(VTOFFSET.wasUserEntered.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var condition: FBSGlucoseCondition { let o = _accessor.offset(VTOFFSET.condition.v); return o == 0 ? .belowRange : FBSGlucoseCondition(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .belowRange }
  public var trendRate: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.trendRate.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public static func startFBSFixtureGlucoseSample(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(provenanceIdentifier: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: provenanceIdentifier, at: VTOFFSET.provenanceIdentifier.p) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(quantity: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: quantity, at: VTOFFSET.quantity.p) }
  public static func add(isDisplayOnly: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isDisplayOnly, def: false,
   at: VTOFFSET.isDisplayOnly.p) }
  public static func add(wasUserEntered: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: wasUserEntered, def: false,
   at: VTOFFSET.wasUserEntered.p) }
  public static func add(condition: FBSGlucoseCondition, _ fbb: inout FlatBufferBuilder) { fbb.add(element: condition.rawValue, def: 0, at: VTOFFSET.condition.p) }
  public static func add(trendRate: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: trendRate, at: VTOFFSET.trendRate.p) }
  public static func endFBSFixtureGlucoseSample(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSFixtureGlucoseSample(
    _ fbb: inout FlatBufferBuilder,
    provenanceIdentifierOffset provenanceIdentifier: Offset = Offset(),
    startDate: Double = 0.0,
    quantityOffset quantity: Offset = Offset(),
    isDisplayOnly: Bool = false,
    wasUserEntered: Bool = false,
    condition: FBSGlucoseCondition = .belowRange,
    trendRateOffset trendRate: Offset = Offset()
  ) -> Offset {
    let __start = FBSFixtureGlucoseSample.startFBSFixtureGlucoseSample(&fbb)
    FBSFixtureGlucoseSample.add(provenanceIdentifier: provenanceIdentifier, &fbb)
    FBSFixtureGlucoseSample.add(startDate: startDate, &fbb)
    FBSFixtureGlucoseSample.add(quantity: quantity, &fbb)
    FBSFixtureGlucoseSample.add(isDisplayOnly: isDisplayOnly, &fbb)
    FBSFixtureGlucoseSample.add(wasUserEntered: wasUserEntered, &fbb)
    FBSFixtureGlucoseSample.add(condition: condition, &fbb)
    FBSFixtureGlucoseSample.add(trendRate: trendRate, &fbb)
    return FBSFixtureGlucoseSample.endFBSFixtureGlucoseSample(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.provenanceIdentifier.p, fieldName: "provenanceIdentifier", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.quantity.p, fieldName: "quantity", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    try _v.visit(field: VTOFFSET.isDisplayOnly.p, fieldName: "isDisplayOnly", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.wasUserEntered.p, fieldName: "wasUserEntered", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.condition.p, fieldName: "condition", required: false, type: FBSGlucoseCondition.self)
    try _v.visit(field: VTOFFSET.trendRate.p, fieldName: "trendRate", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    _v.finish()
  }
}

public struct FBSFixtureInsulinDose: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case deliveryType = 4
    case startDate = 6
    case endDate = 8
    case volume = 10
    case insulinType = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var deliveryType: FBSInsulinDeliveryType { let o = _accessor.offset(VTOFFSET.deliveryType.v); return o == 0 ? .bolus : FBSInsulinDeliveryType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .bolus }
  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var endDate: Double { let o = _accessor.offset(VTOFFSET.endDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var volume: Double { let o = _accessor.offset(VTOFFSET.volume.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var insulinType: FBSFixtureInsulinType { let o = _accessor.offset(VTOFFSET.insulinType.v); return o == 0 ? .novolog : FBSFixtureInsulinType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .novolog }
  public static func startFBSFixtureInsulinDose(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(deliveryType: FBSInsulinDeliveryType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: deliveryType.rawValue, def: 0, at: VTOFFSET.deliveryType.p) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(endDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: endDate, def: 0.0, at: VTOFFSET.endDate.p) }
  public static func add(volume: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: volume, def: 0.0, at: VTOFFSET.volume.p) }
  public static func add(insulinType: FBSFixtureInsulinType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: insulinType.rawValue, def: 0, at: VTOFFSET.insulinType.p) }
  public static func endFBSFixtureInsulinDose(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSFixtureInsulinDose(
    _ fbb: inout FlatBufferBuilder,
    deliveryType: FBSInsulinDeliveryType = .bolus,
    startDate: Double = 0.0,
    endDate: Double = 0.0,
    volume: Double = 0.0,
    insulinType: FBSFixtureInsulinType = .novolog
  ) -> Offset {
    let __start = FBSFixtureInsulinDose.startFBSFixtureInsulinDose(&fbb)
    FBSFixtureInsulinDose.add(deliveryType: deliveryType, &fbb)
    FBSFixtureInsulinDose.add(startDate: startDate, &fbb)
    FBSFixtureInsulinDose.add(endDate: endDate, &fbb)
    FBSFixtureInsulinDose.add(volume: volume, &fbb)
    FBSFixtureInsulinDose.add(insulinType: insulinType, &fbb)
    return FBSFixtureInsulinDose.endFBSFixtureInsulinDose(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.deliveryType.p, fieldName: "deliveryType", required: false, type: FBSInsulinDeliveryType.self)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.endDate.p, fieldName: "endDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.volume.p, fieldName: "volume", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.insulinType.p, fieldName: "insulinType", required: false, type: FBSFixtureInsulinType.self)
    _v.finish()
  }
}

public struct FBSFixtureCarbEntry: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case absorptionTime = 4
    case startDate = 6
    case quantity = 8
    case foodType = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var absorptionTime: Double? { let o = _accessor.offset(VTOFFSET.absorptionTime.v); return o == 0 ? nil : _accessor.readBuffer(of: Double.self, at: o) }
  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var quantity: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.quantity.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public var foodType: String? { let o = _accessor.offset(VTOFFSET.foodType.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var foodTypeSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.foodType.v) }
  public static func startFBSFixtureCarbEntry(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(absorptionTime: Double?, _ fbb: inout FlatBufferBuilder) { fbb.add(element: absorptionTime, at: VTOFFSET.absorptionTime.p) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(quantity: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: quantity, at: VTOFFSET.quantity.p) }
  public static func add(foodType: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: foodType, at: VTOFFSET.foodType.p) }
  public static func endFBSFixtureCarbEntry(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSFixtureCarbEntry(
    _ fbb: inout FlatBufferBuilder,
    absorptionTime: Double? = nil,
    startDate: Double = 0.0,
    quantityOffset quantity: Offset = Offset(),
    foodTypeOffset foodType: Offset = Offset()
  ) -> Offset {
    let __start = FBSFixtureCarbEntry.startFBSFixtureCarbEntry(&fbb)
    FBSFixtureCarbEntry.add(absorptionTime: absorptionTime, &fbb)
    FBSFixtureCarbEntry.add(startDate: startDate, &fbb)
    FBSFixtureCarbEntry.add(quantity: quantity, &fbb)
    FBSFixtureCarbEntry.add(foodType: foodType, &fbb)
    return FBSFixtureCarbEntry.endFBSFixtureCarbEntry(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.absorptionTime.p, fieldName: "absorptionTime", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.quantity.p, fieldName: "quantity", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    try _v.visit(field: VTOFFSET.foodType.p, fieldName: "foodType", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct FBSAbsoluteScheduleValueOfDouble: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case startDate = 4
    case endDate = 6
    case value = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var endDate: Double { let o = _accessor.offset(VTOFFSET.endDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var value: Double { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startFBSAbsoluteScheduleValueOfDouble(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(endDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: endDate, def: 0.0, at: VTOFFSET.endDate.p) }
  public static func add(value: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: value, def: 0.0, at: VTOFFSET.value.p) }
  public static func endFBSAbsoluteScheduleValueOfDouble(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSAbsoluteScheduleValueOfDouble(
    _ fbb: inout FlatBufferBuilder,
    startDate: Double = 0.0,
    endDate: Double = 0.0,
    value: Double = 0.0
  ) -> Offset {
    let __start = FBSAbsoluteScheduleValueOfDouble.startFBSAbsoluteScheduleValueOfDouble(&fbb)
    FBSAbsoluteScheduleValueOfDouble.add(startDate: startDate, &fbb)
    FBSAbsoluteScheduleValueOfDouble.add(endDate: endDate, &fbb)
    FBSAbsoluteScheduleValueOfDouble.add(value: value, &fbb)
    return FBSAbsoluteScheduleValueOfDouble.endFBSAbsoluteScheduleValueOfDouble(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.endDate.p, fieldName: "endDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: Double.self)
    _v.finish()
  }
}

public struct FBSAbsoluteScheduleValueOfLoopQuantity: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case startDate = 4
    case endDate = 6
    case value = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var endDate: Double { let o = _accessor.offset(VTOFFSET.endDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var value: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public static func startFBSAbsoluteScheduleValueOfLoopQuantity(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(endDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: endDate, def: 0.0, at: VTOFFSET.endDate.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endFBSAbsoluteScheduleValueOfLoopQuantity(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSAbsoluteScheduleValueOfLoopQuantity(
    _ fbb: inout FlatBufferBuilder,
    startDate: Double = 0.0,
    endDate: Double = 0.0,
    valueOffset value: Offset = Offset()
  ) -> Offset {
    let __start = FBSAbsoluteScheduleValueOfLoopQuantity.startFBSAbsoluteScheduleValueOfLoopQuantity(&fbb)
    FBSAbsoluteScheduleValueOfLoopQuantity.add(startDate: startDate, &fbb)
    FBSAbsoluteScheduleValueOfLoopQuantity.add(endDate: endDate, &fbb)
    FBSAbsoluteScheduleValueOfLoopQuantity.add(value: value, &fbb)
    return FBSAbsoluteScheduleValueOfLoopQuantity.endFBSAbsoluteScheduleValueOfLoopQuantity(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.endDate.p, fieldName: "endDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    _v.finish()
  }
}

public struct FBSClosedRangeOfLoopQuantity: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case lowerBound = 4
    case upperBound = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var lowerBound: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.lowerBound.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public var upperBound: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.upperBound.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public static func startFBSClosedRangeOfLoopQuantity(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(lowerBound: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: lowerBound, at: VTOFFSET.lowerBound.p) }
  public static func add(upperBound: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: upperBound, at: VTOFFSET.upperBound.p) }
  public static func endFBSClosedRangeOfLoopQuantity(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSClosedRangeOfLoopQuantity(
    _ fbb: inout FlatBufferBuilder,
    lowerBoundOffset lowerBound: Offset = Offset(),
    upperBoundOffset upperBound: Offset = Offset()
  ) -> Offset {
    let __start = FBSClosedRangeOfLoopQuantity.startFBSClosedRangeOfLoopQuantity(&fbb)
    FBSClosedRangeOfLoopQuantity.add(lowerBound: lowerBound, &fbb)
    FBSClosedRangeOfLoopQuantity.add(upperBound: upperBound, &fbb)
    return FBSClosedRangeOfLoopQuantity.endFBSClosedRangeOfLoopQuantity(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.lowerBound.p, fieldName: "lowerBound", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    try _v.visit(field: VTOFFSET.upperBound.p, fieldName: "upperBound", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    _v.finish()
  }
}

public struct FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case startDate = 4
    case endDate = 6
    case value = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var startDate: Double { let o = _accessor.offset(VTOFFSET.startDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var endDate: Double { let o = _accessor.offset(VTOFFSET.endDate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var value: FBSClosedRangeOfLoopQuantity? { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? nil : FBSClosedRangeOfLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public static func startFBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(startDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startDate, def: 0.0, at: VTOFFSET.startDate.p) }
  public static func add(endDate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: endDate, def: 0.0, at: VTOFFSET.endDate.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endFBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(
    _ fbb: inout FlatBufferBuilder,
    startDate: Double = 0.0,
    endDate: Double = 0.0,
    valueOffset value: Offset = Offset()
  ) -> Offset {
    let __start = FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity.startFBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(&fbb)
    FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity.add(startDate: startDate, &fbb)
    FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity.add(endDate: endDate, &fbb)
    FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity.add(value: value, &fbb)
    return FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity.endFBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.startDate.p, fieldName: "startDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.endDate.p, fieldName: "endDate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: ForwardOffset<FBSClosedRangeOfLoopQuantity>.self)
    _v.finish()
  }
}

public struct FBSLoopAlgorithmInputFixture: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_3_25() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case predictionStart = 4
    case glucoseHistory = 6
    case doses = 8
    case carbEntries = 10
    case basal = 12
    case sensitivity = 14
    case carbRatio = 16
    case target = 18
    case suspendThreshold = 20
    case maxBolus = 22
    case maxActiveInsulinMultiplier = 24
    case maxBasalRate = 26
    case useIntegralRetrospectiveCorrection = 28
    case useMidAbsorptionIsf = 30
    case includePositiveVelocityAndRc = 32
    case carbAbsorptionModel = 34
    case recommendationInsulinType = 36
    case recommendationType = 38
    case automaticbolusapplicationfactor = 40
    case gradualtransitionsthreshold = 42
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var predictionStart: Double { let o = _accessor.offset(VTOFFSET.predictionStart.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var hasGlucoseHistory: Bool { let o = _accessor.offset(VTOFFSET.glucoseHistory.v); return o == 0 ? false : true }
  public var glucoseHistoryCount: Int32 { let o = _accessor.offset(VTOFFSET.glucoseHistory.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func glucoseHistory(at index: Int32) -> FBSFixtureGlucoseSample? { let o = _accessor.offset(VTOFFSET.glucoseHistory.v); return o == 0 ? nil : FBSFixtureGlucoseSample(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasDoses: Bool { let o = _accessor.offset(VTOFFSET.doses.v); return o == 0 ? false : true }
  public var dosesCount: Int32 { let o = _accessor.offset(VTOFFSET.doses.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func doses(at index: Int32) -> FBSFixtureInsulinDose? { let o = _accessor.offset(VTOFFSET.doses.v); return o == 0 ? nil : FBSFixtureInsulinDose(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasCarbEntries: Bool { let o = _accessor.offset(VTOFFSET.carbEntries.v); return o == 0 ? false : true }
  public var carbEntriesCount: Int32 { let o = _accessor.offset(VTOFFSET.carbEntries.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func carbEntries(at index: Int32) -> FBSFixtureCarbEntry? { let o = _accessor.offset(VTOFFSET.carbEntries.v); return o == 0 ? nil : FBSFixtureCarbEntry(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasBasal: Bool { let o = _accessor.offset(VTOFFSET.basal.v); return o == 0 ? false : true }
  public var basalCount: Int32 { let o = _accessor.offset(VTOFFSET.basal.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func basal(at index: Int32) -> FBSAbsoluteScheduleValueOfDouble? { let o = _accessor.offset(VTOFFSET.basal.v); return o == 0 ? nil : FBSAbsoluteScheduleValueOfDouble(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasSensitivity: Bool { let o = _accessor.offset(VTOFFSET.sensitivity.v); return o == 0 ? false : true }
  public var sensitivityCount: Int32 { let o = _accessor.offset(VTOFFSET.sensitivity.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func sensitivity(at index: Int32) -> FBSAbsoluteScheduleValueOfLoopQuantity? { let o = _accessor.offset(VTOFFSET.sensitivity.v); return o == 0 ? nil : FBSAbsoluteScheduleValueOfLoopQuantity(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasCarbRatio: Bool { let o = _accessor.offset(VTOFFSET.carbRatio.v); return o == 0 ? false : true }
  public var carbRatioCount: Int32 { let o = _accessor.offset(VTOFFSET.carbRatio.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func carbRatio(at index: Int32) -> FBSAbsoluteScheduleValueOfDouble? { let o = _accessor.offset(VTOFFSET.carbRatio.v); return o == 0 ? nil : FBSAbsoluteScheduleValueOfDouble(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasTarget: Bool { let o = _accessor.offset(VTOFFSET.target.v); return o == 0 ? false : true }
  public var targetCount: Int32 { let o = _accessor.offset(VTOFFSET.target.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func target(at index: Int32) -> FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity? { let o = _accessor.offset(VTOFFSET.target.v); return o == 0 ? nil : FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var suspendThreshold: FBSLoopQuantity? { let o = _accessor.offset(VTOFFSET.suspendThreshold.v); return o == 0 ? nil : FBSLoopQuantity(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
  public var maxBolus: Double { let o = _accessor.offset(VTOFFSET.maxBolus.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var maxActiveInsulinMultiplier: Double? { let o = _accessor.offset(VTOFFSET.maxActiveInsulinMultiplier.v); return o == 0 ? nil : _accessor.readBuffer(of: Double.self, at: o) }
  public var maxBasalRate: Double { let o = _accessor.offset(VTOFFSET.maxBasalRate.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var useIntegralRetrospectiveCorrection: Bool { let o = _accessor.offset(VTOFFSET.useIntegralRetrospectiveCorrection.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var useMidAbsorptionIsf: Bool { let o = _accessor.offset(VTOFFSET.useMidAbsorptionIsf.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var includePositiveVelocityAndRc: Bool { let o = _accessor.offset(VTOFFSET.includePositiveVelocityAndRc.v); return o == 0 ? true : _accessor.readBuffer(of: Bool.self, at: o) }
  public var carbAbsorptionModel: FBSCarbAbsorptionModel { let o = _accessor.offset(VTOFFSET.carbAbsorptionModel.v); return o == 0 ? .piecewiseLinear : FBSCarbAbsorptionModel(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .piecewiseLinear }
  public var recommendationInsulinType: FBSFixtureInsulinType { let o = _accessor.offset(VTOFFSET.recommendationInsulinType.v); return o == 0 ? .novolog : FBSFixtureInsulinType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .novolog }
  public var recommendationType: FBSDoseRecommendationType { let o = _accessor.offset(VTOFFSET.recommendationType.v); return o == 0 ? .automaticBolus : FBSDoseRecommendationType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .automaticBolus }
  public var automaticbolusapplicationfactor: Double? { let o = _accessor.offset(VTOFFSET.automaticbolusapplicationfactor.v); return o == 0 ? nil : _accessor.readBuffer(of: Double.self, at: o) }
  public var gradualtransitionsthreshold: Double { let o = _accessor.offset(VTOFFSET.gradualtransitionsthreshold.v); return o == 0 ? 40.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startFBSLoopAlgorithmInputFixture(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 20) }
  public static func add(predictionStart: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: predictionStart, def: 0.0, at: VTOFFSET.predictionStart.p) }
  public static func addVectorOf(glucoseHistory: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: glucoseHistory, at: VTOFFSET.glucoseHistory.p) }
  public static func addVectorOf(doses: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: doses, at: VTOFFSET.doses.p) }
  public static func addVectorOf(carbEntries: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: carbEntries, at: VTOFFSET.carbEntries.p) }
  public static func addVectorOf(basal: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: basal, at: VTOFFSET.basal.p) }
  public static func addVectorOf(sensitivity: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sensitivity, at: VTOFFSET.sensitivity.p) }
  public static func addVectorOf(carbRatio: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: carbRatio, at: VTOFFSET.carbRatio.p) }
  public static func addVectorOf(target: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: target, at: VTOFFSET.target.p) }
  public static func add(suspendThreshold: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: suspendThreshold, at: VTOFFSET.suspendThreshold.p) }
  public static func add(maxBolus: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxBolus, def: 0.0, at: VTOFFSET.maxBolus.p) }
  public static func add(maxActiveInsulinMultiplier: Double?, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxActiveInsulinMultiplier, at: VTOFFSET.maxActiveInsulinMultiplier.p) }
  public static func add(maxBasalRate: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxBasalRate, def: 0.0, at: VTOFFSET.maxBasalRate.p) }
  public static func add(useIntegralRetrospectiveCorrection: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: useIntegralRetrospectiveCorrection, def: false,
   at: VTOFFSET.useIntegralRetrospectiveCorrection.p) }
  public static func add(useMidAbsorptionIsf: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: useMidAbsorptionIsf, def: false,
   at: VTOFFSET.useMidAbsorptionIsf.p) }
  public static func add(includePositiveVelocityAndRc: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: includePositiveVelocityAndRc, def: true,
   at: VTOFFSET.includePositiveVelocityAndRc.p) }
  public static func add(carbAbsorptionModel: FBSCarbAbsorptionModel, _ fbb: inout FlatBufferBuilder) { fbb.add(element: carbAbsorptionModel.rawValue, def: 1, at: VTOFFSET.carbAbsorptionModel.p) }
  public static func add(recommendationInsulinType: FBSFixtureInsulinType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: recommendationInsulinType.rawValue, def: 0, at: VTOFFSET.recommendationInsulinType.p) }
  public static func add(recommendationType: FBSDoseRecommendationType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: recommendationType.rawValue, def: 1, at: VTOFFSET.recommendationType.p) }
  public static func add(automaticbolusapplicationfactor: Double?, _ fbb: inout FlatBufferBuilder) { fbb.add(element: automaticbolusapplicationfactor, at: VTOFFSET.automaticbolusapplicationfactor.p) }
  public static func add(gradualtransitionsthreshold: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: gradualtransitionsthreshold, def: 40.0, at: VTOFFSET.gradualtransitionsthreshold.p) }
  public static func endFBSLoopAlgorithmInputFixture(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFBSLoopAlgorithmInputFixture(
    _ fbb: inout FlatBufferBuilder,
    predictionStart: Double = 0.0,
    glucoseHistoryVectorOffset glucoseHistory: Offset = Offset(),
    dosesVectorOffset doses: Offset = Offset(),
    carbEntriesVectorOffset carbEntries: Offset = Offset(),
    basalVectorOffset basal: Offset = Offset(),
    sensitivityVectorOffset sensitivity: Offset = Offset(),
    carbRatioVectorOffset carbRatio: Offset = Offset(),
    targetVectorOffset target: Offset = Offset(),
    suspendThresholdOffset suspendThreshold: Offset = Offset(),
    maxBolus: Double = 0.0,
    maxActiveInsulinMultiplier: Double? = nil,
    maxBasalRate: Double = 0.0,
    useIntegralRetrospectiveCorrection: Bool = false,
    useMidAbsorptionIsf: Bool = false,
    includePositiveVelocityAndRc: Bool = true,
    carbAbsorptionModel: FBSCarbAbsorptionModel = .piecewiseLinear,
    recommendationInsulinType: FBSFixtureInsulinType = .novolog,
    recommendationType: FBSDoseRecommendationType = .automaticBolus,
    automaticbolusapplicationfactor: Double? = nil,
    gradualtransitionsthreshold: Double = 40.0
  ) -> Offset {
    let __start = FBSLoopAlgorithmInputFixture.startFBSLoopAlgorithmInputFixture(&fbb)
    FBSLoopAlgorithmInputFixture.add(predictionStart: predictionStart, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(glucoseHistory: glucoseHistory, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(doses: doses, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(carbEntries: carbEntries, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(basal: basal, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(sensitivity: sensitivity, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(carbRatio: carbRatio, &fbb)
    FBSLoopAlgorithmInputFixture.addVectorOf(target: target, &fbb)
    FBSLoopAlgorithmInputFixture.add(suspendThreshold: suspendThreshold, &fbb)
    FBSLoopAlgorithmInputFixture.add(maxBolus: maxBolus, &fbb)
    FBSLoopAlgorithmInputFixture.add(maxActiveInsulinMultiplier: maxActiveInsulinMultiplier, &fbb)
    FBSLoopAlgorithmInputFixture.add(maxBasalRate: maxBasalRate, &fbb)
    FBSLoopAlgorithmInputFixture.add(useIntegralRetrospectiveCorrection: useIntegralRetrospectiveCorrection, &fbb)
    FBSLoopAlgorithmInputFixture.add(useMidAbsorptionIsf: useMidAbsorptionIsf, &fbb)
    FBSLoopAlgorithmInputFixture.add(includePositiveVelocityAndRc: includePositiveVelocityAndRc, &fbb)
    FBSLoopAlgorithmInputFixture.add(carbAbsorptionModel: carbAbsorptionModel, &fbb)
    FBSLoopAlgorithmInputFixture.add(recommendationInsulinType: recommendationInsulinType, &fbb)
    FBSLoopAlgorithmInputFixture.add(recommendationType: recommendationType, &fbb)
    FBSLoopAlgorithmInputFixture.add(automaticbolusapplicationfactor: automaticbolusapplicationfactor, &fbb)
    FBSLoopAlgorithmInputFixture.add(gradualtransitionsthreshold: gradualtransitionsthreshold, &fbb)
    return FBSLoopAlgorithmInputFixture.endFBSLoopAlgorithmInputFixture(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.predictionStart.p, fieldName: "predictionStart", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.glucoseHistory.p, fieldName: "glucoseHistory", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSFixtureGlucoseSample>, FBSFixtureGlucoseSample>>.self)
    try _v.visit(field: VTOFFSET.doses.p, fieldName: "doses", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSFixtureInsulinDose>, FBSFixtureInsulinDose>>.self)
    try _v.visit(field: VTOFFSET.carbEntries.p, fieldName: "carbEntries", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSFixtureCarbEntry>, FBSFixtureCarbEntry>>.self)
    try _v.visit(field: VTOFFSET.basal.p, fieldName: "basal", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSAbsoluteScheduleValueOfDouble>, FBSAbsoluteScheduleValueOfDouble>>.self)
    try _v.visit(field: VTOFFSET.sensitivity.p, fieldName: "sensitivity", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSAbsoluteScheduleValueOfLoopQuantity>, FBSAbsoluteScheduleValueOfLoopQuantity>>.self)
    try _v.visit(field: VTOFFSET.carbRatio.p, fieldName: "carbRatio", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSAbsoluteScheduleValueOfDouble>, FBSAbsoluteScheduleValueOfDouble>>.self)
    try _v.visit(field: VTOFFSET.target.p, fieldName: "target", required: false, type: ForwardOffset<Vector<ForwardOffset<FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity>, FBSAbsoluteScheduleValueOfClosedRangeOfLoopQuantity>>.self)
    try _v.visit(field: VTOFFSET.suspendThreshold.p, fieldName: "suspendThreshold", required: false, type: ForwardOffset<FBSLoopQuantity>.self)
    try _v.visit(field: VTOFFSET.maxBolus.p, fieldName: "maxBolus", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.maxActiveInsulinMultiplier.p, fieldName: "maxActiveInsulinMultiplier", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.maxBasalRate.p, fieldName: "maxBasalRate", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.useIntegralRetrospectiveCorrection.p, fieldName: "useIntegralRetrospectiveCorrection", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.useMidAbsorptionIsf.p, fieldName: "useMidAbsorptionIsf", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.includePositiveVelocityAndRc.p, fieldName: "includePositiveVelocityAndRc", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.carbAbsorptionModel.p, fieldName: "carbAbsorptionModel", required: false, type: FBSCarbAbsorptionModel.self)
    try _v.visit(field: VTOFFSET.recommendationInsulinType.p, fieldName: "recommendationInsulinType", required: false, type: FBSFixtureInsulinType.self)
    try _v.visit(field: VTOFFSET.recommendationType.p, fieldName: "recommendationType", required: false, type: FBSDoseRecommendationType.self)
    try _v.visit(field: VTOFFSET.automaticbolusapplicationfactor.p, fieldName: "automaticbolusapplicationfactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.gradualtransitionsthreshold.p, fieldName: "gradualtransitionsthreshold", required: false, type: Double.self)
    _v.finish()
  }
}

